version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_laravel
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: laravel_password
      POSTGRES_DB: EventManager
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel_network

volumes:
  postgres_data:

networks:
  laravel_network:
    driver: bridge
